# Generated by Django 2.1.dev20180209010235 on 2018-02-21 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=250)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.IntegerField(primary_key=True, serialize=False)),
                ('property_name', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('property_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=50)),
                ('room_description', models.CharField(max_length=250)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('room_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transaction_date', models.DateField()),
                ('transaction_reason', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('transaction_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.Room')),
            ],
        ),
    ]
