# Generated by Django 2.1.dev20180209010235 on 2018-03-12 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_auto_20180227_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasedetails',
            name='lease_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rent.Transaction'),
        ),
    ]
