# Generated by Django 2.1.dev20180209010235 on 2018-03-16 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_leasedetails_lease_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_rent',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leasedetails',
            name='lease_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rent.Transaction'),
        ),
    ]
