# Generated by Django 2.1.dev20180209010235 on 2018-03-28 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_auto_20180316_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electricitymeter',
            fields=[
                ('meter_id', models.AutoField(primary_key=True, serialize=False)),
                ('meter_number', models.CharField(max_length=50)),
                ('meter_description', models.CharField(max_length=250)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rent.Electricitymeter'),
        ),
    ]
